import type { Metadata } from "next";
import { Sometype_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "./elements/MainNav";
import PageTransition from "./elements/PageTransition";
import RectangleTransition from "./elements/RectangleTransition";
import Header from "./elements/Header";


const SometypeMono = Sometype_Mono({
  variable: "--font-sometypeMono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${SometypeMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col xl:overflow-hidden ">
        <RectangleTransition />
        <PageTransition>
        <div className="flex">
           <div className="hidden xl:flex w-71 h-screen bg-secondary">
          <MainNav />
         </div>
        <div className="w-full max-w-282.5 px-3.75 mx-auto">
          <Header />
          <div>{children}</div>
        </div>
        </div>
       </PageTransition>
       
        </body>
    </html>
  );
}
